import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/ui/NavBar";
import PageTransition from "@/ui/PageTransition";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="min-h-screen bg-[#003312dd] font-sans text-[#f6e0ae] flex flex-col">
            <div className="sticky top-0">
                <NavBar
                    options={[
                        {title: 'Home', link: './'},
                        {title: 'Menu', link: './menu'},
                        {title: 'Meet The Kitties', link: './meetTheKitties'},
                        {title: 'Contact Us', link: './contactUs'},
                    ]}
                />
            </div>
            <PageTransition>
                    {children}
            </PageTransition>
        </div>
        </body>
        </html>
    );
}
